//
//  Sound.swift
//  
//  Copyright © 2016-2019 Apple Inc. All rights reserved.
//

import Foundation

/// An enumeration of all the different sounds that can be played.
///
/// - localizationKey: Sound
public enum Sound: String, Codable {
    
    case ahh,
    alien,
    alienGoodbye,
    alienHello,
    alienSirens,
    announcement,
    attack,
    backUp,
    beat,
    beat2,
    bells,
    birds,
    birds1,
    bloops,
    boops,
    boops2,
    beat3,
    brokenGlass,
    canYouHearMe,
    caveBeats,
    chime,
    chord,
    chord2,
    clap,
    clomp,
    comeHere,
    comingTo,
    cowBell,
    creepy,
    creepy2,
    dinnerBell,
    drill,
    droplet2,
    droplet3,
    drums,
    drums2,
    dumDeDum,
    email,
    err,
    eerie,
    eerie1,
    etherial,
    etherial2,
    explosion,
    explosion2,
    flute,
    flute2,
    foundIt,
    galacticChime,
    galacticHorns,
    galacticSonar,
    galacticTelephone,
    gentle,
    getReady,
    glassClink,
    gong,
    gotIt,
    handDrums,
    harp,
    hearMeNow,
    highLow,
    highPitch,
    hits,
    hits2,
    horns,
    horns2,
    horns4,
    jungle,
    labBeats,
    labBeats2,
    layer,
    lightChord,
    lightsUp,
    looking,
    looking3,
    low,
    mission,
    nanana,
    notes,
    notes2,
    offAndAway,
    oneTwoThree,
    piano,
    piano2,
    ping,
    ping2,
    ping3,
    playWithMe,
    pluck,
    powerUp,
    printer,
    ringing,
    shakeItUp,
    shaker,
    sharps,
    shimmer,
    shimmer2,
    shipwreck,
    signals,
    silverware,
    sirens,
    slime,
    sonar2,
    sonar3,
    sonar4,
    sonar5,
    sonarHit,
    sonicSounds,
    sonicSounds2,
    sonicSounds3,
    spaceCarnival,
    spaceGuitar,
    spaceHorns,
    spaceInvaders,
    spaceTrance,
    steelDrums,
    steelDrums2,
    stickDrop,
    symbols,
    symbols2,
    symbols3,
    tapTap,
    taps,
    teslaCoil,
    thinking,
    thinking2,
    thud,
    thud2,
    thudSonar,
    tide,
    tide2,
    tink,
    tinkTink,
    tuneIn,
    twinkles,
    underwaterThud,
    vibrations2,
    vocals,
    waaaa,
    warble,
    weeOoo,
    weirdDinnerBell,
    weirdHits,
    weirdYoga,
    whaleSounds,
    windDown,
    windUp,
    windUp2,
    ratchet,
    yoga,
    yoga2,
    yoga3,
    zip
    
    public var url : URL? {
        return Bundle.main.url(forResource: rawValue, withExtension: "m4a")
    }
}
/// An enumeration of the different types of Music you can play.
///
/// - localizationKey: Music
public enum Music: String {
    
    case cave, turtle, underwater, lab
    
    public var url : URL? {
        return Bundle.main.url(forResource: rawValue, withExtension: "m4a")
    }
}

